### ISSUE TITLE
version compare between tgf terragrunt with gruntwork-io/terragrunt

### ISSUE THREAD

**Issue by Tiny-wlx** [coveooss/tgf#77]
Hi all,

I have used terragrunt in my env with version v0.18.7 at gruntwork-io/terragrunt,
i want use tgf now, Which version should i use with the same vesion.
when i use the latest vesion(terragrunt version 1.3.7/), it showed some errror.

Thanks.

**Comment by jocgir** [comment]
We forked the original project long ago and added a lot of features to it. See [terragrunt](https://github.com/coveo/terragrunt).

It is mostly compatible. What kind of error do you get?

**Comment by Tiny-wlx** [comment]
Hi @jocgir 

Because we use terragrunt v0.18.7, we know if we use the latest version of terragrunt, we should modify out codes to adapt the changes, so we want to use the terragrunt v0.18.7, but which version should we use with tgf, and if the version have ssh installed?

Thank you

**Comment by jocgir** [comment]
Since terragrunt is bundled with the image, you would have to override it by creating a custom image.

You can do it with the following command in your tgf.config file:

```
docker-image-build: |
   curl -sLo/usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.18.7/terragrunt_linux_amd64 && chmod +x /usr/local/bin/terragrunt
```

**Comment by Tiny-wlx** [comment]
Hi @jocgir ,

Thank you very much, i will try next few days.

Thanks
